tk_list_homepage:
    pattern:  /lists
    defaults: { _controller: TkListBundle:List:index }

tk_list_details:
    pattern: /lists/{id}
    defaults: { _controller: TkListBundle:List:details }

tk_list_new:
    pattern: /new/lists
    defaults: { _controller: TkListBundle:List:new }