<?php

namespace Tk\ListBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShoppingItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingItemRepository extends EntityRepository
{
}
